import type { Metadata } from 'next';
import './globals.css';
import { lightTheme, darkTheme } from './globals.css';

export const metadata: Metadata = {
  title: 'INVADER',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' className={lightTheme}>
      <body className={darkTheme}>
        {children}
      </body>
    </html>
  );
}
